### ISSUE TITLE
PHHueSDK leaves an open thread

### ISSUE THREAD

**Issue by chms** [PhilipsHue/PhilipsHueSDK-Java-MultiPlatform-Android#13]
I don't know if this is a wanted effect, but even when destroying the PHHueSDK, there remains an open thread. Consider the following Java program

```Java
import com.philips.lighting.hue.sdk.PHHueSDK;

public class Test {
	public static void main(String[] args) {
		// Create SDK
		PHHueSDK phHueSDK = PHHueSDK.create();
		
		// Main code
		System.out.println("Do main task");

		// Exit program
		phHueSDK.disableAllHeartbeat();
		phHueSDK.destroySDK();
	}
}
```

It won't exit unless you add a `System.exit(0)` at the end because there will be a thread `[Timer-0]` even after you "Clean up resources held by the SDK" through `destroySDK()`.

**Comment by SteveyO** [comment]
Sorry for not replying to this earlier.  I did check but forgot to post back.  This issue was reported on the forum today so I posted a reply there.

http://www.developers.meethue.com/content/java-program-wont-exit-hue-sdk-active

**Comment by SteveyO** [comment]
The fix for this has just been committed. If you take any of the new huelocalsdk.jar files (either from the QuickStart or JavaDesktop app lib folders) then the Timer thread is now killed when calling the destroySDK method.
