### ISSUE TITLE
Updating LightState with 'on' value fails unintuitively

### ISSUE THREAD

**Issue by J-Swift** [PhilipsHue/PhilipsHueSDK-Java-MultiPlatform-Android#14]
In the application I'm working on, I send state updates in 'full frames'. That is, I set the 'on', 'transitiontime', 'hue', 'saturation', and 'brightness' in one call. I've found that when I try to do this for a light which is off, I need to initially send an 'on' update with transtiontime of 0 in order to then get the other updates to work well. I do that using something like the following:

```java
final PHLightState state = light.getLastKnownLightState();
final Runnable afterOnRunnable = new Runnable() {
    public void run() {
        state.setHue(hue);
        state.setSaturation(saturation);
        state.setBrightness(brightness);
        state.setTransitionTime(transitionTime);
        bridge.updateLightState( light, state );
    }
}

if ( state.isOn() ) {
    afterOnRunnable.run();
    return;
}
        
state.setTransitionTime( 0 );
state.setOn( true );
bridge.updateLightState( light, state, new PHLightListener() {
    public void onSuccess() {
        afterOnRunnable.run();
    }
    ...
});
        
```

I've found that if the light is already on then this fails in the runnable's call to updateLightState, presumably because I'm trying to 're-set' the on value. When I log out the 'onError' callback information it says:

```
code: 6
message: parameter, reachable, not available
```

If I change the code to use a new `PHLightState` within the runnable, and take care not to set an on value, then it runs fine. This seems to go against the note in [the documentation](http://www.developers.meethue.com/documentation/java-sdk-getting-started#changingColors) that you can update the light state by 1) retrieving the last known light state 2) updating the value you want to change and 3) sending the update to the bridge.

Am I wrong in my understanding of how to go about updating these values, or is this something that could be addressed?

**Comment by J-Swift** [comment]
OK, thanks Steve. Hopefully the new notes save someone a bit of time down the road.

**Comment by SteveyO** [comment]
No problem.   Yeah,  hopefully clearer for all now.   I will close this issue now!
