### ISSUE TITLE
PHUtilities.calculateXYFromRGB doesn't support Gamut C (Hue Go)

### ISSUE THREAD

**Issue by J-Swift** [PhilipsHue/PhilipsHueSDK-Java-MultiPlatform-Android#18]
I had a look at the source and it appears there isn't a `colorPoints` definition for Gamut C devices. This means it will end up with the default `colorPoints` definition, which is less than ideal. Is Gamut C slated for a future update? If so, when would you expect to publish that?

Thanks!

**Comment by SteveyO** [comment]
Hi,
Yes, the Gamut C is coming in the next update (along with some other 1.7 functionality, e.g. delete lights and some new attributes ).  I currently don't have a release date.
As soon as I have a release date I will let you know.  Hopefully soon!

Steve

**Comment by J-Swift** [comment]
OK, thanks Steve. I'll keep an eye out for that.

**Comment by SteveyO** [comment]
We have just released the Java 1.8 SDK.   This includes Gamut C (Hue Go).  So just pick up the 2 new .jar files (huelocalsdk.jar and huesdkresources.jar) from either the QuickStart App or Java Desktop app lib folders and hopefully everything should work out.   Let me know if you have any issues.
Steve
