### ISSUE TITLE
Can I use HUE API in MATLAB?

### ISSUE THREAD

**Issue by tYami** [PhilipsHue/PhilipsHueSDK-Java-MultiPlatform-Android#22]
Hello,

I'm trying to control Hue with diverse way. However, SDK is provided as only Apple or JAVA style.
Unfortunately, I am not familiar with those environment. So, I want to use them or another SDK for MATLAB program.

So.... is there any possible way to use JAVA API in MATLAB?

**Comment by SteveyO** [comment]
Hi there,

I have never used MATLAB, so I can't comment on whether integration with Hue is possible.  The only things I can suggest is if you are not comfortable with our Rest API, Objective-C or Java then you could try out one of the 3rd Party Libraries.  There are many in various languages, so you could try the one you are most comfortable with and see if they work with matlab.

http://www.developers.meethue.com/tools-and-sdks

You could also try posting this question on the our forums,   if you are lucky you may find one of our community members has experience in this.
www.developers.meethue.com/forum

Good  luck
Steve
