### ISSUE TITLE
Open source API

### ISSUE THREAD

**Issue by jespersmith** [PhilipsHue/PhilipsHueSDK-Java-MultiPlatform-Android#23]
While the example applications are open source, I cannot recompile the libraries in lib/. Is there any plan open sourcing these API's?

**Comment by SteveyO** [comment]
Hi Jesper,

There is no immediate plan on open sourcing the SDKs.  If this changes in the future then any announcement would be made on: www.developers.meethue.com

The current Java SDK is pretty much up-to-date with the latest bridge firmware,  however if you have a feature request (which I assume is the reason for you wanting to re-compile the libs) then drop us a line and we will evaluate it.

Thanks
Steve

**Comment by jespersmith** [comment]
Steve,

Main reason to want an open source library is easy distribution with a GPL licensed project as a single bundle. 

Jesper
