### ISSUE TITLE
phBridge.getScene() not available in sdk 1.2.0

### ISSUE THREAD

**Issue by jeroenbeuz** [PhilipsHue/PhilipsHueSDK-Java-MultiPlatform-Android#38]
The new sdk version 1.2.0 does not have the getScene() method, to get a scene with it's lightstates. The method is completely gone in the PHBridge class. The PHGroupClass is also gone from the SDK. What happened? Did these get relocated?

**Comment by jhvdb87** [comment]
The problem is fixed in the 1.20.1 release.

**Comment by gkamperis** [comment]
This was built with a different Java version target than the previous library.
Most Android development is NOT Java 8.

**Comment by danzada1** [comment]
Yes I am also having trouble compiling due to Java 8. Can you please rebuild with Java 7?

**Comment by jhvdb87** [comment]
I changed the compliance level back to 1.6.

**Comment by gkamperis** [comment]
Works great!
Thanks
